binutils: Update to 2.34
Fix:
    Running bitarray-1.2.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-c0bchezq/bitarray-1.2.1/egg-dist-tmp-7uv2m7jm
    warning: build_py: byte-compiling is disabled, skipping.

    build/conda/compiler_compat/ld: build/temp.linux-x86_64-3.7/bitarray/_bitarray.o: unable to initialize decompress status for section .debug_info
    build/temp.linux-x86_64-3.7/bitarray/_bitarray.o: file not recognized: file format not recognized
    collect2: error: ld returned 1 exit status
    error: Setup script exited with error: command 'gcc' failed with exit status 1

See:
    https://bbs.archlinux.org/viewtopic.php?id=242682